// Generated by https://quicktype.io

namespace DataMedic.Infrastructure.Portainer;

using System;
using System.Collections.Generic;

using System.Globalization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

public partial class PortainerContainerDetailResponse
{
    [JsonProperty("AppArmorProfile")]
    public string AppArmorProfile { get; set; }

    [JsonProperty("Args")]
    public string[] Args { get; set; }

    [JsonProperty("Config")]
    public PortainerContainerDetailResponseConfig Config { get; set; }

    [JsonProperty("Created")]
    public DateTimeOffset Created { get; set; }

    [JsonProperty("Driver")]
    public string Driver { get; set; }

    [JsonProperty("ExecIDs")]
    public object ExecIDs { get; set; }

    [JsonProperty("GraphDriver")]
    public GraphDriver GraphDriver { get; set; }

    [JsonProperty("HostConfig")]
    public HostConfig HostConfig { get; set; }

    [JsonProperty("HostnamePath")]
    public string HostnamePath { get; set; }

    [JsonProperty("HostsPath")]
    public string HostsPath { get; set; }

    [JsonProperty("Id")]
    public string Id { get; set; }

    [JsonProperty("Image")]
    public string Image { get; set; }

    [JsonProperty("LogPath")]
    public string LogPath { get; set; }

    [JsonProperty("MountLabel")]
    public string MountLabel { get; set; }

    [JsonProperty("Mounts")]
    public PortainerContainerDetailResponseMount[] Mounts { get; set; }

    [JsonProperty("Name")]
    public string Name { get; set; }


    [JsonProperty("Path")]
    public string Path { get; set; }

    [JsonProperty("Platform")]
    public string Platform { get; set; }

    [JsonProperty("ProcessLabel")]
    public string ProcessLabel { get; set; }

    [JsonProperty("ResolvConfPath")]
    public string ResolvConfPath { get; set; }

    [JsonProperty("RestartCount")]
    public long RestartCount { get; set; }

    [JsonProperty("State")]
    public ContainerState State { get; set; }
}

public partial class PortainerContainerDetailResponseConfig
{
    [JsonProperty("AttachStderr")]
    public bool AttachStderr { get; set; }

    [JsonProperty("AttachStdin")]
    public bool AttachStdin { get; set; }

    [JsonProperty("AttachStdout")]
    public bool AttachStdout { get; set; }

    [JsonProperty("Cmd")]
    public string[] Cmd { get; set; }

    [JsonProperty("Domainname")]
    public string Domainname { get; set; }

    [JsonProperty("Entrypoint")]
    public object Entrypoint { get; set; }

    [JsonProperty("Env")]
    public string[] Env { get; set; }

    [JsonProperty("Hostname")]
    public string Hostname { get; set; }

    [JsonProperty("Image")]
    public string Image { get; set; }

    [JsonProperty("Labels")]
    public Dictionary<string, string> Labels { get; set; }

    [JsonProperty("OnBuild")]
    public object OnBuild { get; set; }

    [JsonProperty("OpenStdin")]
    public bool OpenStdin { get; set; }

    [JsonProperty("StdinOnce")]
    public bool StdinOnce { get; set; }

    [JsonProperty("Tty")]
    public bool Tty { get; set; }

    [JsonProperty("User")]
    public string User { get; set; }

    [JsonProperty("Volumes")]
    public object Volumes { get; set; }

    [JsonProperty("WorkingDir")]
    public string WorkingDir { get; set; }
}

public partial class GraphDriver
{
    [JsonProperty("Data")]
    public Data Data { get; set; }

    [JsonProperty("Name")]
    public string Name { get; set; }
}

public partial class Data
{
    [JsonProperty("dir")]
    public string Dir { get; set; }
}

public partial class HostConfig
{
    [JsonProperty("AutoRemove")]
    public bool AutoRemove { get; set; }

    [JsonProperty("Binds")]
    public object[] Binds { get; set; }

    [JsonProperty("BlkioDeviceReadBps")]
    public object BlkioDeviceReadBps { get; set; }

    [JsonProperty("BlkioDeviceReadIOps")]
    public object BlkioDeviceReadIOps { get; set; }

    [JsonProperty("BlkioDeviceWriteBps")]
    public object BlkioDeviceWriteBps { get; set; }

    [JsonProperty("BlkioDeviceWriteIOps")]
    public object BlkioDeviceWriteIOps { get; set; }

    [JsonProperty("BlkioWeight")]
    public long BlkioWeight { get; set; }

    [JsonProperty("BlkioWeightDevice")]
    public object BlkioWeightDevice { get; set; }

    [JsonProperty("CapAdd")]
    public object CapAdd { get; set; }

    [JsonProperty("CapDrop")]
    public object CapDrop { get; set; }

    [JsonProperty("Cgroup")]
    public string Cgroup { get; set; }

    [JsonProperty("CgroupParent")]
    public string CgroupParent { get; set; }

    [JsonProperty("CgroupnsMode")]
    public string CgroupnsMode { get; set; }

    [JsonProperty("ConsoleSize")]
    public long[] ConsoleSize { get; set; }

    [JsonProperty("ContainerIDFile")]
    public string ContainerIdFile { get; set; }

    [JsonProperty("CpuCount")]
    public long CpuCount { get; set; }

    [JsonProperty("CpuPercent")]
    public long CpuPercent { get; set; }

    [JsonProperty("CpuPeriod")]
    public long CpuPeriod { get; set; }

    [JsonProperty("CpuQuota")]
    public long CpuQuota { get; set; }

    [JsonProperty("CpuRealtimePeriod")]
    public long CpuRealtimePeriod { get; set; }

    [JsonProperty("CpuRealtimeRuntime")]
    public long CpuRealtimeRuntime { get; set; }

    [JsonProperty("CpuShares")]
    public long CpuShares { get; set; }

    [JsonProperty("CpusetCpus")]
    public string CpusetCpus { get; set; }

    [JsonProperty("CpusetMems")]
    public string CpusetMems { get; set; }

    [JsonProperty("DeviceCgroupRules")]
    public object DeviceCgroupRules { get; set; }

    [JsonProperty("DeviceRequests")]
    public object DeviceRequests { get; set; }

    [JsonProperty("Devices")]
    public object Devices { get; set; }

    [JsonProperty("Dns")]
    public object[] Dns { get; set; }

    [JsonProperty("DnsOptions")]
    public object[] DnsOptions { get; set; }

    [JsonProperty("DnsSearch")]
    public object[] DnsSearch { get; set; }

    [JsonProperty("ExtraHosts")]
    public object ExtraHosts { get; set; }

    [JsonProperty("GroupAdd")]
    public object GroupAdd { get; set; }

    [JsonProperty("IOMaximumBandwidth")]
    public long IoMaximumBandwidth { get; set; }

    [JsonProperty("IOMaximumIOps")]
    public long IoMaximumIOps { get; set; }

    [JsonProperty("IpcMode")]
    public string IpcMode { get; set; }

    [JsonProperty("Isolation")]
    public string Isolation { get; set; }

    [JsonProperty("KernelMemory")]
    public long KernelMemory { get; set; }

    [JsonProperty("KernelMemoryTCP")]
    public long KernelMemoryTcp { get; set; }

    [JsonProperty("Links")]
    public object Links { get; set; }

    [JsonProperty("LogConfig")]
    public LogConfig LogConfig { get; set; }

    [JsonProperty("MaskedPaths")]
    public object MaskedPaths { get; set; }

    [JsonProperty("Memory")]
    public long Memory { get; set; }

    [JsonProperty("MemoryReservation")]
    public long MemoryReservation { get; set; }

    [JsonProperty("MemorySwap")]
    public long MemorySwap { get; set; }

    [JsonProperty("MemorySwappiness")]
    public object MemorySwappiness { get; set; }

    [JsonProperty("Mounts")]
    public HostConfigMount[] Mounts { get; set; }

    [JsonProperty("NanoCpus")]
    public long NanoCpus { get; set; }

    [JsonProperty("OomKillDisable")]
    public object OomKillDisable { get; set; }

    [JsonProperty("OomScoreAdj")]
    public long OomScoreAdj { get; set; }

    [JsonProperty("PidMode")]
    public string PidMode { get; set; }

    [JsonProperty("PidsLimit")]
    public object PidsLimit { get; set; }

    [JsonProperty("PortBindings")]
    public Port PortBindings { get; set; }

    [JsonProperty("Privileged")]
    public bool Privileged { get; set; }

    [JsonProperty("PublishAllPorts")]
    public bool PublishAllPorts { get; set; }

    [JsonProperty("ReadonlyPaths")]
    public object ReadonlyPaths { get; set; }

    [JsonProperty("ReadonlyRootfs")]
    public bool ReadonlyRootfs { get; set; }

    [JsonProperty("RestartPolicy")]
    public RestartPolicy RestartPolicy { get; set; }

    [JsonProperty("SecurityOpt")]
    public object SecurityOpt { get; set; }

    [JsonProperty("ShmSize")]
    public long ShmSize { get; set; }

    [JsonProperty("UTSMode")]
    public string UtsMode { get; set; }

    [JsonProperty("Ulimits")]
    public object Ulimits { get; set; }

    [JsonProperty("UsernsMode")]
    public string UsernsMode { get; set; }

    [JsonProperty("VolumeDriver")]
    public string VolumeDriver { get; set; }

    [JsonProperty("VolumesFrom")]
    public object[] VolumesFrom { get; set; }
}

public partial class LogConfig
{
    [JsonProperty("Config")]
    public LogConfigConfig Config { get; set; }

    [JsonProperty("Type")]
    public string Type { get; set; }
}

public partial class LogConfigConfig
{
    [JsonProperty("max-size")]
    public string MaxSize { get; set; }
}

public partial class HostConfigMount
{
    [JsonProperty("Source")]
    public string Source { get; set; }

    [JsonProperty("Target")]
    public string Target { get; set; }

    [JsonProperty("Type")]
    public string Type { get; set; }
}

public partial class Port { }

public partial class RestartPolicy
{
    [JsonProperty("MaximumRetryCount")]
    public long MaximumRetryCount { get; set; }

    [JsonProperty("Name")]
    public string Name { get; set; }
}

public partial class PortainerContainerDetailResponseMount
{
    [JsonProperty("Destination")]
    public string Destination { get; set; }

    [JsonProperty("Mode")]
    public string Mode { get; set; }

    [JsonProperty("Propagation")]
    public string Propagation { get; set; }

    [JsonProperty("RW")]
    public bool Rw { get; set; }

    [JsonProperty("Source")]
    public string Source { get; set; }

    [JsonProperty("Type")]
    public string Type { get; set; }
}

public partial class NetworkSettings
{
    [JsonProperty("Bridge")]
    public string Bridge { get; set; }

    [JsonProperty("EndpointID")]
    public string EndpointId { get; set; }

    [JsonProperty("Gateway")]
    public string Gateway { get; set; }

    [JsonProperty("GlobalIPv6Address")]
    public string GlobalIPv6Address { get; set; }

    [JsonProperty("GlobalIPv6PrefixLen")]
    public long GlobalIPv6PrefixLen { get; set; }

    [JsonProperty("HairpinMode")]
    public bool HairpinMode { get; set; }

    [JsonProperty("IPAddress")]
    public string IpAddress { get; set; }

    [JsonProperty("IPPrefixLen")]
    public long IpPrefixLen { get; set; }

    [JsonProperty("IPv6Gateway")]
    public string IPv6Gateway { get; set; }

    [JsonProperty("LinkLocalIPv6Address")]
    public string LinkLocalIPv6Address { get; set; }

    [JsonProperty("LinkLocalIPv6PrefixLen")]
    public long LinkLocalIPv6PrefixLen { get; set; }

    [JsonProperty("MacAddress")]
    public string MacAddress { get; set; }

    [JsonProperty("Ports")]
    public Port Ports { get; set; }

    [JsonProperty("SandboxID")]
    public string SandboxId { get; set; }

    [JsonProperty("SandboxKey")]
    public string SandboxKey { get; set; }

    [JsonProperty("SecondaryIPAddresses")]
    public object SecondaryIpAddresses { get; set; }

    [JsonProperty("SecondaryIPv6Addresses")]
    public object SecondaryIPv6Addresses { get; set; }
}

public partial class ContainerState
{
    [JsonProperty("Dead")]
    public bool Dead { get; set; }

    [JsonProperty("Error")]
    public string Error { get; set; }

    [JsonProperty("ExitCode")]
    public long ExitCode { get; set; }

    [JsonProperty("FinishedAt")]
    public DateTimeOffset FinishedAt { get; set; }

    [JsonProperty("OOMKilled")]
    public bool OomKilled { get; set; }

    [JsonProperty("Paused")]
    public bool Paused { get; set; }

    [JsonProperty("Pid")]
    public long Pid { get; set; }

    [JsonProperty("Restarting")]
    public bool Restarting { get; set; }

    [JsonProperty("Running")]
    public bool Running { get; set; }

    [JsonProperty("StartedAt")]
    public DateTimeOffset StartedAt { get; set; }

    [JsonProperty("Status")]
    public string Status { get; set; }
}

public partial class PortainerContainerDetailResponse
{
    public static PortainerContainerDetailResponse? FromJson(string json) =>
        JsonConvert.DeserializeObject<PortainerContainerDetailResponse>(
            json,
            PortainerContainerDetailResponseConverter.Settings
        );
}

internal static class PortainerContainerDetailResponseConverter
{
    public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
    {
        MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
        DateParseHandling = DateParseHandling.None,
        Converters =
        {
            new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
        },
    };
}
