version: "3.9"
services:
  api:
    image: "data-medic/backend:api"
    networks:
      - computing_overlay
  worker:
    image: "data-medic/backend:worker"
    ports:
      - "5010:80"
    logging:
      driver: json-file
      options:
        max-size: 1m
    networks:
      - computing_overlay
networks:
  computing_overlay:
    external: true
    name: computing_overlay
