POST https://localhost:7274/api/v1/sensors
Content-Type: application/json

{
  "HostId": "c65b866e-97e1-4ec4-9858-366a718bb6a4",
  "DeviceComponentId": "B3CB7EE2-59EC-4642-844A-E77289ED9BC6",
  "Description": "",
  "DeviceId": "0b2a4bf6-c805-4802-83e2-72569bed3708",
  "SensorDetail": {
    "Type": 3,
    "FlowId": "flowId",
    "ScanPeriodInMinutes": 10,
  }
}